version: '3.1'

services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /app
    volumes:
      - './docker_setup/mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pet_node
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'

  app:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=pet_node
